name: hw1_env
dependencies:
  - python
  - pip
  - pip:
    - pandas==1.5.3
    - scikit-learn==1.2.2
    - scipy==1.9.3
    - seaborn==0.12.2
    - matplotlib==3.6.3
    - numpy==1.23.5
    - xgboost==1.7.5
    - imbalanced-learn==0.10.1
    - tqdm==4.64.1